# Site settings
title: "DFIR TNT | Digital Forensics | Incident Response | Tips and Tricks"
description: "Digital Forensics | Incident Response | Tips and Tricks"
url: "https://dfirtnt.github.io"
baseurl: ""

# Theme
theme: minima

# Site author
author:
  name: "Andrew Skatoff"
  bio: "Digital Forensics and Incident Response"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

# Collections
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true

# Sitemap
sitemap: true
